Proposition d'amélioration d'activités :
Humanistica/TaDiRAH pull request #6
Opened 2017-09-27 08:08 UTC by PonteIneptique

- Quelques changements de traduction (assez rare : Gestion de projet plutôt que supervision, OCR expliqué en francais, ajout de par exemple pour les sites web)
- Quand remarqué, la reprise des noms dans leur forme originale pour les techniques, objets et activités. (cf. https://github.com/dhtaxonomy/TaDiRAH/issues/18)

2017-09-27 10:16 UTC, aurelberra requested changes
* Deux ou trois modifications indiscutables.
* Quelques options générales à discuter.
* Un grand merci pour la *close reading* !

2017-09-27 10:16 UTC, aurelberra commented on fre/activites.md
> +La Reconnaissance de données, la Reconnaissance Optique de Caractères (ROC ou plus généralement OCR) par exemple, désigne le processus qui consiste à traiter les résultats immédiats de l'acquisition
* Reconnaissance Optique de Caractères > Reconnaissance optique de caractères
* (ROC ou plus généralement OCR) : je ne crois pas que notre rôle soit d'ajouter et d'expliciter, car c'est une traduction…

2017-09-27 10:16 UTC, aurelberra commented on fre/activites.md
> +L'Analyse de contenu est une méthode qui vise à analyser des aspects des objets numériques en rapport avec leur signification, par exemple en identifiant des concepts ou des unités signifiantes. Les
Dans toutes les modifications qui suivent, je ne comprends pas l'ajout de guillemets : elles ne sont pas la convention d'écriture des autres versions (les majuscules signalent les catégories).

D'accord pour le singulier à "information".

2017-09-27 10:16 UTC, aurelberra commented on fre/activites.md
> +L'Analyse de réseaux est une méthode permettant d'étudier les relations d'acteurs (réels ou fictifs) ou d'autres entités au sein d'un réseau donné, qui peut prendre la forme d'un réseau en ligne, que
Ne pas ajouter de guillemets.

2017-09-27 10:16 UTC, aurelberra commented on fre/activites.md
> +L'Analyse relationnelle consiste en des techniques computationnelles destinées à découvrir des relations particulières entre plusieurs objets de recherche. Dans les études textuelles, il peut s'agir
Ne pas ajouter de guillemets.

2017-09-27 10:16 UTC, aurelberra commented on fre/activites.md
> +L'Analyse spatiale est la découverte, dans les données, de tendances ou de formes relatives à leurs aspects spatiaux ou géographiques. Elle se fonde souvent sur des techniques d'"Annotation" des donn
Ne pas ajouter de guillemets.

A priori, j'ai respecté l'usage de la source : parfois il y a une majuscule et c'est un usage technique, parfois il n'y en a pas et ce n'est pas une référence à la catégorie de Tadirah. Même si l'anglais n'est pas tout à fait cohérent, je crois que ce n'est pas notre rôle d'harmoniser – ou alors il faut le faire aussi dans la source.

2017-09-27 10:16 UTC, aurelberra commented on fre/activites.md
> +L'Analyse structurelle consiste en l'analyse d'objets sur le plan des relations entre les éléments structurels d'un artéfact culturel (en linguistique, niveau de la morphologie ou de la syntaxe). Les
"Annotation des parties du discours" : bien vu, c'est notre équivalent dans les Techniques !

Ne pas ajouter de guillemets.

2017-09-27 10:16 UTC, aurelberra commented on fre/activites.md
> +L'Analyse stylistique consiste à identifier les caractéristiques stylistiques ou formelles d'objets numériques. Bien que la stylistique computationnelle soit dans bien des cas appliquée à des textes
Ne pas ajouter de guillemets. – Ici, je vois que tu en as mis à certains termes seulement : quelle était ta logique ?

2017-09-27 10:16 UTC, aurelberra commented on fre/activites.md
> +La Visualisation concerne des activités qui visent à résumer et à présenter sous une forme graphique, ainsi qu'à utiliser ces formes graphiques d'une manière analytique, c'est-à-dire afin de détecter
Ne pas ajouter de guillemets.

2017-09-27 10:16 UTC, aurelberra commented on fre/activites.md
> +La Modélisation est l'activité qui consiste à créer une représentation abstraite d'un phénomène complexe, ordinairement sous une forme lisible par les machines et éventuellement sous une forme intera
L'anglais n'est pas "ResearchProcess". Faut-il normaliser et introduire la catégorie ? Dans ce cas, je pense qu'il faut corriger aussi la source.

2017-09-27 10:16 UTC, aurelberra commented on fre/activites.md
> +L'Organisation concerne l'arrangement des objets (matériaux de recherche, jeux de données, images, etc.) d'une façon qui facilite d'autres activités de recherche. Elle peut également comprendre des a
Ce n'est pas notre rôle d'introduire la référence aux catégories. Ou alors il faut le faire dans la source.

Ne pas ajouter de guillemets.

2017-09-27 10:16 UTC, aurelberra commented on fre/activites.md
> +La Conservation est l'application de stratégies, d'activités et de technologies spécifiques en vue de garantir qu'un contenu numérique sera correctement rendu au fil du temps. Elle facilite le réempl
Le saut de ligne était une erreur : *well spotted* !

Ne pas ajouter de guillemets. (Attention à la séquence « :" Bit ».)

2017-09-27 10:16 UTC, aurelberra commented on fre/activites.md
> +La Dissémination est l'activité qui consiste à rendre disponibles des objets d'enquête, des résultats de recherche ou des logiciels et des services à l'intention de collègues chercheurs ou d'un publi
"la mise en place de données liées ouvertes" > "la mise en œuvre de données liées ouvertes"

Cela simplifie un peu, mais reste opaque, je trouve. L'expression "application of linked open data" était un peu curieuse. Du point de vue du sens, je préfère encore "l'application des principes des données liées ouvertes". Arguments ?

2017-09-27 10:16 UTC, aurelberra commented on fre/activites.md
> +La Collaboration est pratiquée dans toute activité de recherche réalisée conjointement par plusieurs chercheurs, éventuellement en différents lieux et à différents moments. Une collaboration dans une
L'anglais est "Digital Research Environments", avec espaces, et non "VRE", qui est le terme technique défini dans les listes. À corriger dans la source, si nous corrigeons ici…

Ne pas ajouter de guillemets, surtout à des emplois non techniques.

2017-09-27 10:16 UTC, aurelberra commented on fre/activites.md
> +Le Commentaire est l'activité qui consiste à ajouter des informations à un élément de données, habituellement d'une manière qui maintient une séparation entre les données auxquelles le commentaire es
Ne pas ajouter de guillemets.

2017-09-27 10:16 UTC, aurelberra commented on fre/activites.md
> +Le Crowdsourcing, ou production participative, est le paradigme de la génération de contenu par les utilisateurs dans le cadre du Web 2.0, ici appliquée au domaine de la recherche en humanités numéri
Ne pas ajouter de guillemets.

2017-09-27 10:16 UTC, aurelberra commented on fre/activites.md
> +Les Méta-activités sont des activités qui, contrairement aux activités de recherche habituelles, ne concernent pas directement un objet de recherche, mais plutôt la combinaison d'une activité de rech
Ici, les guillemets sont bien dans la source. En revanche, l'anglais est "Digital Humanities" et non la catégorie "DigitalHumanities". D'où notre problème habituel. Corriger ici et dans la source ?

2017-09-27 10:16 UTC, aurelberra commented on fre/activites.md
> +La Construction de communauté (*Community building*) est l'activité qui consiste à créer ou à développer une communauté fondée sur un intérêt partagé. Il peut comprendre la "Dissémination" et l'ensei
Ne pas ajouter de guillemets. Pas un terme technique dans la source…

2017-09-27 10:16 UTC, aurelberra commented on fre/activites.md
> +La Gestion de projet (*Project management*) comprend des activités telles que développer une stratégie et évaluer les risques, ou encore assurer la gestion des tâches, en documentant les tâches, les
Tout à fait d'accord !

En revanche, ne pas ajouter de guillemets à "Collaboration".

2017-09-29 05:28 UTC, PonteIneptique commented on fre/activites.md
> +La Reconnaissance de données, la Reconnaissance Optique de Caractères (ROC ou plus généralement OCR) par exemple, désigne le processus qui consiste à traiter les résultats immédiats de l'acquisition
Je suis d'accord et en même temps, Ocr est plus connu que roc.

2017-09-29 06:25 UTC, aurelberra commented on fre/activites.md
> +La Reconnaissance de données, la Reconnaissance Optique de Caractères (ROC ou plus généralement OCR) par exemple, désigne le processus qui consiste à traiter les résultats immédiats de l'acquisition
D'accord pour adapter légèrement. Je propose ceci :

> La Reconnaissance de données, par exemple la reconnaissance optique de caractères (ROC, en anglais OCR)

2017-10-11 14:27 UTC, PonteIneptique commented on fre/activites.md
> +La Gestion de projet (*Project management*) comprend des activités telles que développer une stratégie et évaluer les risques, ou encore assurer la gestion des tâches, en documentant les tâches, les
En même temps, l'espagnol donne ce lien : http://vocabularyserver.com/tadirah/es/index.php?tema=53&/gestion-de-proyectos

2017-10-11 15:20 UTC, aurelberra commented on fre/activites.md
> +La Modélisation est l'activité qui consiste à créer une représentation abstraite d'un phénomène complexe, ordinairement sous une forme lisible par les machines et éventuellement sous une forme intera
Garder "Processus", même si l'anglais semble introduire une catégorie implicitement.

2017-10-11 15:27 UTC, PonteIneptique commented on fre/activites.md
> +L'Organisation concerne l'arrangement des objets (matériaux de recherche, jeux de données, images, etc.) d'une façon qui facilite d'autres activités de recherche. Elle peut également comprendre des a
> "Création" de "Métadonnées" et leur amélioration ("Enrichissement").

2017-10-11 15:38 UTC, merged